### ISSUE TITLE
[Feature request] Max and min length support in schemas definition

### ISSUE THREAD

**Issue by KBeDevel** [antoniopresto/powership#7]
Without wishes of getting out of scope, it would be useful to include a content length validation in the schema definition itself.

As long as I know, there is no way to validate the content length using any of the provided validation functions in the schema implementation.

For this reason, I propose to extend the current schema field definition object by adding the `maxLength` and `minLength` properties, both typed as `number | undefined`.

Example:

```typescript
const SampleSchema = createSchema({
  sampleField: {
    type: 'string',
    minLength: 5,
    maxLength: 30
  }
})

const sampleObject: Infer<typeof SampleSchema> = {
  sampleField: 'foo'
}
```

Results on:

```typescript
SampleSchema.parse(sampleObject) // Should throw "RangeError: the value length (3) of field 'sampleField' is lower than the minimum expected length (5)."
```

**Comment by antoniopresto** [comment]
Hi! Thanks for filling this issue!

I think is more a documentation problem 😅

You can do it like:
```ts

const SampleSchema = createSchema({
  sampleField: {
    string: {
      min: 5,
      max: 30,
      // regex: ['^w{1,30}$', 'mig'], // <- also valid
    },
  },
});

```

I preferred to standardize the common structure between the types and leave the specific settings for each type in the "def" of each one.

You can use [regex, min, max ](https://github.com/antoniopresto/powership/blob/09bfeed31088252c7ff60d5b010df99c4ed894f7/packages/schema/src/fields/StringField.ts#L6-L10) for strings - other types may have other specific settings, keeping the common definition simple - and keeping typescript calm 🧘🏽.

**Comment by antoniopresto** [comment]
all types: https://github.com/antoniopresto/powership/tree/5a2a88b5bd30dad8df1abd2dc746b4c8eaf7bdc7/packages/schema/src/fields

**Comment by KBeDevel** [comment]
Nice to know, thank you.
